// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BackendsColumns holds the columns for the "backends" table.
	BackendsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "external_id", Type: field.TypeString, Unique: true},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// BackendsTable holds the schema information for the "backends" table.
	BackendsTable = &schema.Table{
		Name:       "backends",
		Columns:    BackendsColumns,
		PrimaryKey: []*schema.Column{BackendsColumns[0]},
	}
	// BackendUsersColumns holds the columns for the "backend_users" table.
	BackendUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "backend_user_id", Type: field.TypeString},
		{Name: "backend_token", Type: field.TypeString, Nullable: true},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "backend_backend_users", Type: field.TypeUUID},
		{Name: "user_backend_users", Type: field.TypeUUID},
	}
	// BackendUsersTable holds the schema information for the "backend_users" table.
	BackendUsersTable = &schema.Table{
		Name:       "backend_users",
		Columns:    BackendUsersColumns,
		PrimaryKey: []*schema.Column{BackendUsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "backend_users_backends_backend_users",
				Columns:    []*schema.Column{BackendUsersColumns[4]},
				RefColumns: []*schema.Column{BackendsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "backend_users_users_backend_users",
				Columns:    []*schema.Column{BackendUsersColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "backenduser_user_backend_users_backend_backend_users",
				Unique:  true,
				Columns: []*schema.Column{BackendUsersColumns[5], BackendUsersColumns[4]},
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "token", Type: field.TypeString, Unique: true},
		{Name: "device_id", Type: field.TypeString},
		{Name: "device_name", Type: field.TypeString},
		{Name: "app_name", Type: field.TypeString},
		{Name: "app_version", Type: field.TypeString, Nullable: true},
		{Name: "last_activity", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_sessions", Type: field.TypeUUID},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sessions_users_sessions",
				Columns:    []*schema.Column{SessionsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "session_token",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[1]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "display_name", Type: field.TypeString},
		{Name: "hashed_password", Type: field.TypeString},
		{Name: "is_admin", Type: field.TypeBool, Default: false},
		{Name: "direct_stream", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "avatar", Type: field.TypeBytes, Nullable: true},
		{Name: "avatar_content_type", Type: field.TypeString, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BackendsTable,
		BackendUsersTable,
		SessionsTable,
		UsersTable,
	}
)

func init() {
	BackendUsersTable.ForeignKeys[0].RefTable = BackendsTable
	BackendUsersTable.ForeignKeys[1].RefTable = UsersTable
	SessionsTable.ForeignKeys[0].RefTable = UsersTable
}
