// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ddevcap/jellyfin-proxy/ent/backend"
	"github.com/ddevcap/jellyfin-proxy/ent/backenduser"
	"github.com/google/uuid"
)

// BackendCreate is the builder for creating a Backend entity.
type BackendCreate struct {
	config
	mutation *BackendMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *BackendCreate) SetName(v string) *BackendCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *BackendCreate) SetURL(v string) *BackendCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetJellyfinServerID sets the "jellyfin_server_id" field.
func (_c *BackendCreate) SetJellyfinServerID(v string) *BackendCreate {
	_c.mutation.SetJellyfinServerID(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *BackendCreate) SetEnabled(v bool) *BackendCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *BackendCreate) SetNillableEnabled(v *bool) *BackendCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BackendCreate) SetCreatedAt(v time.Time) *BackendCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BackendCreate) SetNillableCreatedAt(v *time.Time) *BackendCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BackendCreate) SetID(v uuid.UUID) *BackendCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *BackendCreate) SetNillableID(v *uuid.UUID) *BackendCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddBackendUserIDs adds the "backend_users" edge to the BackendUser entity by IDs.
func (_c *BackendCreate) AddBackendUserIDs(ids ...uuid.UUID) *BackendCreate {
	_c.mutation.AddBackendUserIDs(ids...)
	return _c
}

// AddBackendUsers adds the "backend_users" edges to the BackendUser entity.
func (_c *BackendCreate) AddBackendUsers(v ...*BackendUser) *BackendCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBackendUserIDs(ids...)
}

// Mutation returns the BackendMutation object of the builder.
func (_c *BackendCreate) Mutation() *BackendMutation {
	return _c.mutation
}

// Save creates the Backend in the database.
func (_c *BackendCreate) Save(ctx context.Context) (*Backend, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BackendCreate) SaveX(ctx context.Context) *Backend {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BackendCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BackendCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BackendCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := backend.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := backend.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := backend.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BackendCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Backend.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := backend.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Backend.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Backend.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := backend.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Backend.url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.JellyfinServerID(); !ok {
		return &ValidationError{Name: "jellyfin_server_id", err: errors.New(`ent: missing required field "Backend.jellyfin_server_id"`)}
	}
	if v, ok := _c.mutation.JellyfinServerID(); ok {
		if err := backend.JellyfinServerIDValidator(v); err != nil {
			return &ValidationError{Name: "jellyfin_server_id", err: fmt.Errorf(`ent: validator failed for field "Backend.jellyfin_server_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Backend.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Backend.created_at"`)}
	}
	return nil
}

func (_c *BackendCreate) sqlSave(ctx context.Context) (*Backend, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BackendCreate) createSpec() (*Backend, *sqlgraph.CreateSpec) {
	var (
		_node = &Backend{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(backend.Table, sqlgraph.NewFieldSpec(backend.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(backend.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(backend.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.JellyfinServerID(); ok {
		_spec.SetField(backend.FieldJellyfinServerID, field.TypeString, value)
		_node.JellyfinServerID = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(backend.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(backend.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.BackendUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backend.BackendUsersTable,
			Columns: []string{backend.BackendUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backenduser.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BackendCreateBulk is the builder for creating many Backend entities in bulk.
type BackendCreateBulk struct {
	config
	err      error
	builders []*BackendCreate
}

// Save creates the Backend entities in the database.
func (_c *BackendCreateBulk) Save(ctx context.Context) ([]*Backend, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Backend, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BackendMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BackendCreateBulk) SaveX(ctx context.Context) []*Backend {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BackendCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BackendCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
