// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ddevcap/jellymux/ent/backend"
	"github.com/ddevcap/jellymux/ent/backenduser"
	"github.com/ddevcap/jellymux/ent/predicate"
	"github.com/google/uuid"
)

// BackendQuery is the builder for querying Backend entities.
type BackendQuery struct {
	config
	ctx              *QueryContext
	order            []backend.OrderOption
	inters           []Interceptor
	predicates       []predicate.Backend
	withBackendUsers *BackendUserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BackendQuery builder.
func (_q *BackendQuery) Where(ps ...predicate.Backend) *BackendQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *BackendQuery) Limit(limit int) *BackendQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *BackendQuery) Offset(offset int) *BackendQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *BackendQuery) Unique(unique bool) *BackendQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *BackendQuery) Order(o ...backend.OrderOption) *BackendQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryBackendUsers chains the current query on the "backend_users" edge.
func (_q *BackendQuery) QueryBackendUsers() *BackendUserQuery {
	query := (&BackendUserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(backend.Table, backend.FieldID, selector),
			sqlgraph.To(backenduser.Table, backenduser.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, backend.BackendUsersTable, backend.BackendUsersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Backend entity from the query.
// Returns a *NotFoundError when no Backend was found.
func (_q *BackendQuery) First(ctx context.Context) (*Backend, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{backend.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *BackendQuery) FirstX(ctx context.Context) *Backend {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Backend ID from the query.
// Returns a *NotFoundError when no Backend ID was found.
func (_q *BackendQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{backend.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *BackendQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Backend entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Backend entity is found.
// Returns a *NotFoundError when no Backend entities are found.
func (_q *BackendQuery) Only(ctx context.Context) (*Backend, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{backend.Label}
	default:
		return nil, &NotSingularError{backend.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *BackendQuery) OnlyX(ctx context.Context) *Backend {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Backend ID in the query.
// Returns a *NotSingularError when more than one Backend ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *BackendQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{backend.Label}
	default:
		err = &NotSingularError{backend.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *BackendQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Backends.
func (_q *BackendQuery) All(ctx context.Context) ([]*Backend, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Backend, *BackendQuery]()
	return withInterceptors[[]*Backend](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *BackendQuery) AllX(ctx context.Context) []*Backend {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Backend IDs.
func (_q *BackendQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(backend.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *BackendQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *BackendQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*BackendQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *BackendQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *BackendQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *BackendQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BackendQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *BackendQuery) Clone() *BackendQuery {
	if _q == nil {
		return nil
	}
	return &BackendQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]backend.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.Backend{}, _q.predicates...),
		withBackendUsers: _q.withBackendUsers.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithBackendUsers tells the query-builder to eager-load the nodes that are connected to
// the "backend_users" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BackendQuery) WithBackendUsers(opts ...func(*BackendUserQuery)) *BackendQuery {
	query := (&BackendUserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBackendUsers = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Backend.Query().
//		GroupBy(backend.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *BackendQuery) GroupBy(field string, fields ...string) *BackendGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BackendGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = backend.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Backend.Query().
//		Select(backend.FieldName).
//		Scan(ctx, &v)
func (_q *BackendQuery) Select(fields ...string) *BackendSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &BackendSelect{BackendQuery: _q}
	sbuild.label = backend.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BackendSelect configured with the given aggregations.
func (_q *BackendQuery) Aggregate(fns ...AggregateFunc) *BackendSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *BackendQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !backend.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *BackendQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Backend, error) {
	var (
		nodes       = []*Backend{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withBackendUsers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Backend).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Backend{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withBackendUsers; query != nil {
		if err := _q.loadBackendUsers(ctx, query, nodes,
			func(n *Backend) { n.Edges.BackendUsers = []*BackendUser{} },
			func(n *Backend, e *BackendUser) { n.Edges.BackendUsers = append(n.Edges.BackendUsers, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *BackendQuery) loadBackendUsers(ctx context.Context, query *BackendUserQuery, nodes []*Backend, init func(*Backend), assign func(*Backend, *BackendUser)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Backend)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.BackendUser(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(backend.BackendUsersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.backend_backend_users
		if fk == nil {
			return fmt.Errorf(`foreign-key "backend_backend_users" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "backend_backend_users" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *BackendQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *BackendQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(backend.Table, backend.Columns, sqlgraph.NewFieldSpec(backend.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, backend.FieldID)
		for i := range fields {
			if fields[i] != backend.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *BackendQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(backend.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = backend.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BackendGroupBy is the group-by builder for Backend entities.
type BackendGroupBy struct {
	selector
	build *BackendQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *BackendGroupBy) Aggregate(fns ...AggregateFunc) *BackendGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *BackendGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BackendQuery, *BackendGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *BackendGroupBy) sqlScan(ctx context.Context, root *BackendQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BackendSelect is the builder for selecting fields of Backend entities.
type BackendSelect struct {
	*BackendQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *BackendSelect) Aggregate(fns ...AggregateFunc) *BackendSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *BackendSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BackendQuery, *BackendSelect](ctx, _s.BackendQuery, _s, _s.inters, v)
}

func (_s *BackendSelect) sqlScan(ctx context.Context, root *BackendQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
