// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ddevcap/jellymux/ent/backend"
	"github.com/ddevcap/jellymux/ent/backenduser"
	"github.com/ddevcap/jellymux/ent/predicate"
	"github.com/ddevcap/jellymux/ent/user"
	"github.com/google/uuid"
)

// BackendUserUpdate is the builder for updating BackendUser entities.
type BackendUserUpdate struct {
	config
	hooks    []Hook
	mutation *BackendUserMutation
}

// Where appends a list predicates to the BackendUserUpdate builder.
func (_u *BackendUserUpdate) Where(ps ...predicate.BackendUser) *BackendUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBackendUserID sets the "backend_user_id" field.
func (_u *BackendUserUpdate) SetBackendUserID(v string) *BackendUserUpdate {
	_u.mutation.SetBackendUserID(v)
	return _u
}

// SetNillableBackendUserID sets the "backend_user_id" field if the given value is not nil.
func (_u *BackendUserUpdate) SetNillableBackendUserID(v *string) *BackendUserUpdate {
	if v != nil {
		_u.SetBackendUserID(*v)
	}
	return _u
}

// SetBackendToken sets the "backend_token" field.
func (_u *BackendUserUpdate) SetBackendToken(v string) *BackendUserUpdate {
	_u.mutation.SetBackendToken(v)
	return _u
}

// SetNillableBackendToken sets the "backend_token" field if the given value is not nil.
func (_u *BackendUserUpdate) SetNillableBackendToken(v *string) *BackendUserUpdate {
	if v != nil {
		_u.SetBackendToken(*v)
	}
	return _u
}

// ClearBackendToken clears the value of the "backend_token" field.
func (_u *BackendUserUpdate) ClearBackendToken() *BackendUserUpdate {
	_u.mutation.ClearBackendToken()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *BackendUserUpdate) SetEnabled(v bool) *BackendUserUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *BackendUserUpdate) SetNillableEnabled(v *bool) *BackendUserUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *BackendUserUpdate) SetUserID(id uuid.UUID) *BackendUserUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *BackendUserUpdate) SetUser(v *User) *BackendUserUpdate {
	return _u.SetUserID(v.ID)
}

// SetBackendID sets the "backend" edge to the Backend entity by ID.
func (_u *BackendUserUpdate) SetBackendID(id uuid.UUID) *BackendUserUpdate {
	_u.mutation.SetBackendID(id)
	return _u
}

// SetBackend sets the "backend" edge to the Backend entity.
func (_u *BackendUserUpdate) SetBackend(v *Backend) *BackendUserUpdate {
	return _u.SetBackendID(v.ID)
}

// Mutation returns the BackendUserMutation object of the builder.
func (_u *BackendUserUpdate) Mutation() *BackendUserMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BackendUserUpdate) ClearUser() *BackendUserUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearBackend clears the "backend" edge to the Backend entity.
func (_u *BackendUserUpdate) ClearBackend() *BackendUserUpdate {
	_u.mutation.ClearBackend()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BackendUserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BackendUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BackendUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BackendUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BackendUserUpdate) check() error {
	if v, ok := _u.mutation.BackendUserID(); ok {
		if err := backenduser.BackendUserIDValidator(v); err != nil {
			return &ValidationError{Name: "backend_user_id", err: fmt.Errorf(`ent: validator failed for field "BackendUser.backend_user_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BackendUser.user"`)
	}
	if _u.mutation.BackendCleared() && len(_u.mutation.BackendIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BackendUser.backend"`)
	}
	return nil
}

func (_u *BackendUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backenduser.Table, backenduser.Columns, sqlgraph.NewFieldSpec(backenduser.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BackendUserID(); ok {
		_spec.SetField(backenduser.FieldBackendUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BackendToken(); ok {
		_spec.SetField(backenduser.FieldBackendToken, field.TypeString, value)
	}
	if _u.mutation.BackendTokenCleared() {
		_spec.ClearField(backenduser.FieldBackendToken, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(backenduser.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backenduser.UserTable,
			Columns: []string{backenduser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backenduser.UserTable,
			Columns: []string{backenduser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BackendCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backenduser.BackendTable,
			Columns: []string{backenduser.BackendColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backend.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BackendIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backenduser.BackendTable,
			Columns: []string{backenduser.BackendColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backend.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backenduser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BackendUserUpdateOne is the builder for updating a single BackendUser entity.
type BackendUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BackendUserMutation
}

// SetBackendUserID sets the "backend_user_id" field.
func (_u *BackendUserUpdateOne) SetBackendUserID(v string) *BackendUserUpdateOne {
	_u.mutation.SetBackendUserID(v)
	return _u
}

// SetNillableBackendUserID sets the "backend_user_id" field if the given value is not nil.
func (_u *BackendUserUpdateOne) SetNillableBackendUserID(v *string) *BackendUserUpdateOne {
	if v != nil {
		_u.SetBackendUserID(*v)
	}
	return _u
}

// SetBackendToken sets the "backend_token" field.
func (_u *BackendUserUpdateOne) SetBackendToken(v string) *BackendUserUpdateOne {
	_u.mutation.SetBackendToken(v)
	return _u
}

// SetNillableBackendToken sets the "backend_token" field if the given value is not nil.
func (_u *BackendUserUpdateOne) SetNillableBackendToken(v *string) *BackendUserUpdateOne {
	if v != nil {
		_u.SetBackendToken(*v)
	}
	return _u
}

// ClearBackendToken clears the value of the "backend_token" field.
func (_u *BackendUserUpdateOne) ClearBackendToken() *BackendUserUpdateOne {
	_u.mutation.ClearBackendToken()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *BackendUserUpdateOne) SetEnabled(v bool) *BackendUserUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *BackendUserUpdateOne) SetNillableEnabled(v *bool) *BackendUserUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *BackendUserUpdateOne) SetUserID(id uuid.UUID) *BackendUserUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *BackendUserUpdateOne) SetUser(v *User) *BackendUserUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetBackendID sets the "backend" edge to the Backend entity by ID.
func (_u *BackendUserUpdateOne) SetBackendID(id uuid.UUID) *BackendUserUpdateOne {
	_u.mutation.SetBackendID(id)
	return _u
}

// SetBackend sets the "backend" edge to the Backend entity.
func (_u *BackendUserUpdateOne) SetBackend(v *Backend) *BackendUserUpdateOne {
	return _u.SetBackendID(v.ID)
}

// Mutation returns the BackendUserMutation object of the builder.
func (_u *BackendUserUpdateOne) Mutation() *BackendUserMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *BackendUserUpdateOne) ClearUser() *BackendUserUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearBackend clears the "backend" edge to the Backend entity.
func (_u *BackendUserUpdateOne) ClearBackend() *BackendUserUpdateOne {
	_u.mutation.ClearBackend()
	return _u
}

// Where appends a list predicates to the BackendUserUpdate builder.
func (_u *BackendUserUpdateOne) Where(ps ...predicate.BackendUser) *BackendUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BackendUserUpdateOne) Select(field string, fields ...string) *BackendUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BackendUser entity.
func (_u *BackendUserUpdateOne) Save(ctx context.Context) (*BackendUser, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BackendUserUpdateOne) SaveX(ctx context.Context) *BackendUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BackendUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BackendUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BackendUserUpdateOne) check() error {
	if v, ok := _u.mutation.BackendUserID(); ok {
		if err := backenduser.BackendUserIDValidator(v); err != nil {
			return &ValidationError{Name: "backend_user_id", err: fmt.Errorf(`ent: validator failed for field "BackendUser.backend_user_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BackendUser.user"`)
	}
	if _u.mutation.BackendCleared() && len(_u.mutation.BackendIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BackendUser.backend"`)
	}
	return nil
}

func (_u *BackendUserUpdateOne) sqlSave(ctx context.Context) (_node *BackendUser, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backenduser.Table, backenduser.Columns, sqlgraph.NewFieldSpec(backenduser.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BackendUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, backenduser.FieldID)
		for _, f := range fields {
			if !backenduser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != backenduser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BackendUserID(); ok {
		_spec.SetField(backenduser.FieldBackendUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BackendToken(); ok {
		_spec.SetField(backenduser.FieldBackendToken, field.TypeString, value)
	}
	if _u.mutation.BackendTokenCleared() {
		_spec.ClearField(backenduser.FieldBackendToken, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(backenduser.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backenduser.UserTable,
			Columns: []string{backenduser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backenduser.UserTable,
			Columns: []string{backenduser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BackendCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backenduser.BackendTable,
			Columns: []string{backenduser.BackendColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backend.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BackendIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backenduser.BackendTable,
			Columns: []string{backenduser.BackendColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backend.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BackendUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backenduser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
