// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ddevcap/jellyfin-proxy/ent/backend"
	"github.com/ddevcap/jellyfin-proxy/ent/backenduser"
	"github.com/ddevcap/jellyfin-proxy/ent/predicate"
	"github.com/google/uuid"
)

// BackendUpdate is the builder for updating Backend entities.
type BackendUpdate struct {
	config
	hooks    []Hook
	mutation *BackendMutation
}

// Where appends a list predicates to the BackendUpdate builder.
func (_u *BackendUpdate) Where(ps ...predicate.Backend) *BackendUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *BackendUpdate) SetName(v string) *BackendUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BackendUpdate) SetNillableName(v *string) *BackendUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *BackendUpdate) SetURL(v string) *BackendUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *BackendUpdate) SetNillableURL(v *string) *BackendUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetJellyfinServerID sets the "jellyfin_server_id" field.
func (_u *BackendUpdate) SetJellyfinServerID(v string) *BackendUpdate {
	_u.mutation.SetJellyfinServerID(v)
	return _u
}

// SetNillableJellyfinServerID sets the "jellyfin_server_id" field if the given value is not nil.
func (_u *BackendUpdate) SetNillableJellyfinServerID(v *string) *BackendUpdate {
	if v != nil {
		_u.SetJellyfinServerID(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *BackendUpdate) SetEnabled(v bool) *BackendUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *BackendUpdate) SetNillableEnabled(v *bool) *BackendUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// AddBackendUserIDs adds the "backend_users" edge to the BackendUser entity by IDs.
func (_u *BackendUpdate) AddBackendUserIDs(ids ...uuid.UUID) *BackendUpdate {
	_u.mutation.AddBackendUserIDs(ids...)
	return _u
}

// AddBackendUsers adds the "backend_users" edges to the BackendUser entity.
func (_u *BackendUpdate) AddBackendUsers(v ...*BackendUser) *BackendUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBackendUserIDs(ids...)
}

// Mutation returns the BackendMutation object of the builder.
func (_u *BackendUpdate) Mutation() *BackendMutation {
	return _u.mutation
}

// ClearBackendUsers clears all "backend_users" edges to the BackendUser entity.
func (_u *BackendUpdate) ClearBackendUsers() *BackendUpdate {
	_u.mutation.ClearBackendUsers()
	return _u
}

// RemoveBackendUserIDs removes the "backend_users" edge to BackendUser entities by IDs.
func (_u *BackendUpdate) RemoveBackendUserIDs(ids ...uuid.UUID) *BackendUpdate {
	_u.mutation.RemoveBackendUserIDs(ids...)
	return _u
}

// RemoveBackendUsers removes "backend_users" edges to BackendUser entities.
func (_u *BackendUpdate) RemoveBackendUsers(v ...*BackendUser) *BackendUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBackendUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BackendUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BackendUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BackendUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BackendUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BackendUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := backend.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Backend.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := backend.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Backend.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.JellyfinServerID(); ok {
		if err := backend.JellyfinServerIDValidator(v); err != nil {
			return &ValidationError{Name: "jellyfin_server_id", err: fmt.Errorf(`ent: validator failed for field "Backend.jellyfin_server_id": %w`, err)}
		}
	}
	return nil
}

func (_u *BackendUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backend.Table, backend.Columns, sqlgraph.NewFieldSpec(backend.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(backend.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(backend.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.JellyfinServerID(); ok {
		_spec.SetField(backend.FieldJellyfinServerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(backend.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.BackendUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backend.BackendUsersTable,
			Columns: []string{backend.BackendUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backenduser.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBackendUsersIDs(); len(nodes) > 0 && !_u.mutation.BackendUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backend.BackendUsersTable,
			Columns: []string{backend.BackendUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backenduser.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BackendUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backend.BackendUsersTable,
			Columns: []string{backend.BackendUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backenduser.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backend.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BackendUpdateOne is the builder for updating a single Backend entity.
type BackendUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BackendMutation
}

// SetName sets the "name" field.
func (_u *BackendUpdateOne) SetName(v string) *BackendUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *BackendUpdateOne) SetNillableName(v *string) *BackendUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *BackendUpdateOne) SetURL(v string) *BackendUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *BackendUpdateOne) SetNillableURL(v *string) *BackendUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetJellyfinServerID sets the "jellyfin_server_id" field.
func (_u *BackendUpdateOne) SetJellyfinServerID(v string) *BackendUpdateOne {
	_u.mutation.SetJellyfinServerID(v)
	return _u
}

// SetNillableJellyfinServerID sets the "jellyfin_server_id" field if the given value is not nil.
func (_u *BackendUpdateOne) SetNillableJellyfinServerID(v *string) *BackendUpdateOne {
	if v != nil {
		_u.SetJellyfinServerID(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *BackendUpdateOne) SetEnabled(v bool) *BackendUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *BackendUpdateOne) SetNillableEnabled(v *bool) *BackendUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// AddBackendUserIDs adds the "backend_users" edge to the BackendUser entity by IDs.
func (_u *BackendUpdateOne) AddBackendUserIDs(ids ...uuid.UUID) *BackendUpdateOne {
	_u.mutation.AddBackendUserIDs(ids...)
	return _u
}

// AddBackendUsers adds the "backend_users" edges to the BackendUser entity.
func (_u *BackendUpdateOne) AddBackendUsers(v ...*BackendUser) *BackendUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBackendUserIDs(ids...)
}

// Mutation returns the BackendMutation object of the builder.
func (_u *BackendUpdateOne) Mutation() *BackendMutation {
	return _u.mutation
}

// ClearBackendUsers clears all "backend_users" edges to the BackendUser entity.
func (_u *BackendUpdateOne) ClearBackendUsers() *BackendUpdateOne {
	_u.mutation.ClearBackendUsers()
	return _u
}

// RemoveBackendUserIDs removes the "backend_users" edge to BackendUser entities by IDs.
func (_u *BackendUpdateOne) RemoveBackendUserIDs(ids ...uuid.UUID) *BackendUpdateOne {
	_u.mutation.RemoveBackendUserIDs(ids...)
	return _u
}

// RemoveBackendUsers removes "backend_users" edges to BackendUser entities.
func (_u *BackendUpdateOne) RemoveBackendUsers(v ...*BackendUser) *BackendUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBackendUserIDs(ids...)
}

// Where appends a list predicates to the BackendUpdate builder.
func (_u *BackendUpdateOne) Where(ps ...predicate.Backend) *BackendUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BackendUpdateOne) Select(field string, fields ...string) *BackendUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Backend entity.
func (_u *BackendUpdateOne) Save(ctx context.Context) (*Backend, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BackendUpdateOne) SaveX(ctx context.Context) *Backend {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BackendUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BackendUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BackendUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := backend.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Backend.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := backend.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Backend.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.JellyfinServerID(); ok {
		if err := backend.JellyfinServerIDValidator(v); err != nil {
			return &ValidationError{Name: "jellyfin_server_id", err: fmt.Errorf(`ent: validator failed for field "Backend.jellyfin_server_id": %w`, err)}
		}
	}
	return nil
}

func (_u *BackendUpdateOne) sqlSave(ctx context.Context) (_node *Backend, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(backend.Table, backend.Columns, sqlgraph.NewFieldSpec(backend.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Backend.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, backend.FieldID)
		for _, f := range fields {
			if !backend.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != backend.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(backend.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(backend.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.JellyfinServerID(); ok {
		_spec.SetField(backend.FieldJellyfinServerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(backend.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.BackendUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backend.BackendUsersTable,
			Columns: []string{backend.BackendUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backenduser.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBackendUsersIDs(); len(nodes) > 0 && !_u.mutation.BackendUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backend.BackendUsersTable,
			Columns: []string{backend.BackendUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backenduser.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BackendUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   backend.BackendUsersTable,
			Columns: []string{backend.BackendUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backenduser.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Backend{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{backend.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
