// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ddevcap/jellymux/ent/backend"
	"github.com/ddevcap/jellymux/ent/backenduser"
	"github.com/ddevcap/jellymux/ent/user"
	"github.com/google/uuid"
)

// BackendUserCreate is the builder for creating a BackendUser entity.
type BackendUserCreate struct {
	config
	mutation *BackendUserMutation
	hooks    []Hook
}

// SetBackendUserID sets the "backend_user_id" field.
func (_c *BackendUserCreate) SetBackendUserID(v string) *BackendUserCreate {
	_c.mutation.SetBackendUserID(v)
	return _c
}

// SetBackendToken sets the "backend_token" field.
func (_c *BackendUserCreate) SetBackendToken(v string) *BackendUserCreate {
	_c.mutation.SetBackendToken(v)
	return _c
}

// SetNillableBackendToken sets the "backend_token" field if the given value is not nil.
func (_c *BackendUserCreate) SetNillableBackendToken(v *string) *BackendUserCreate {
	if v != nil {
		_c.SetBackendToken(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *BackendUserCreate) SetEnabled(v bool) *BackendUserCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *BackendUserCreate) SetNillableEnabled(v *bool) *BackendUserCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BackendUserCreate) SetID(v uuid.UUID) *BackendUserCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *BackendUserCreate) SetNillableID(v *uuid.UUID) *BackendUserCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *BackendUserCreate) SetUserID(id uuid.UUID) *BackendUserCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *BackendUserCreate) SetUser(v *User) *BackendUserCreate {
	return _c.SetUserID(v.ID)
}

// SetBackendID sets the "backend" edge to the Backend entity by ID.
func (_c *BackendUserCreate) SetBackendID(id uuid.UUID) *BackendUserCreate {
	_c.mutation.SetBackendID(id)
	return _c
}

// SetBackend sets the "backend" edge to the Backend entity.
func (_c *BackendUserCreate) SetBackend(v *Backend) *BackendUserCreate {
	return _c.SetBackendID(v.ID)
}

// Mutation returns the BackendUserMutation object of the builder.
func (_c *BackendUserCreate) Mutation() *BackendUserMutation {
	return _c.mutation
}

// Save creates the BackendUser in the database.
func (_c *BackendUserCreate) Save(ctx context.Context) (*BackendUser, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BackendUserCreate) SaveX(ctx context.Context) *BackendUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BackendUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BackendUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BackendUserCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := backenduser.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := backenduser.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BackendUserCreate) check() error {
	if _, ok := _c.mutation.BackendUserID(); !ok {
		return &ValidationError{Name: "backend_user_id", err: errors.New(`ent: missing required field "BackendUser.backend_user_id"`)}
	}
	if v, ok := _c.mutation.BackendUserID(); ok {
		if err := backenduser.BackendUserIDValidator(v); err != nil {
			return &ValidationError{Name: "backend_user_id", err: fmt.Errorf(`ent: validator failed for field "BackendUser.backend_user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "BackendUser.enabled"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "BackendUser.user"`)}
	}
	if len(_c.mutation.BackendIDs()) == 0 {
		return &ValidationError{Name: "backend", err: errors.New(`ent: missing required edge "BackendUser.backend"`)}
	}
	return nil
}

func (_c *BackendUserCreate) sqlSave(ctx context.Context) (*BackendUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BackendUserCreate) createSpec() (*BackendUser, *sqlgraph.CreateSpec) {
	var (
		_node = &BackendUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(backenduser.Table, sqlgraph.NewFieldSpec(backenduser.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.BackendUserID(); ok {
		_spec.SetField(backenduser.FieldBackendUserID, field.TypeString, value)
		_node.BackendUserID = value
	}
	if value, ok := _c.mutation.BackendToken(); ok {
		_spec.SetField(backenduser.FieldBackendToken, field.TypeString, value)
		_node.BackendToken = &value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(backenduser.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backenduser.UserTable,
			Columns: []string{backenduser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_backend_users = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BackendIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   backenduser.BackendTable,
			Columns: []string{backenduser.BackendColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(backend.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.backend_backend_users = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BackendUserCreateBulk is the builder for creating many BackendUser entities in bulk.
type BackendUserCreateBulk struct {
	config
	err      error
	builders []*BackendUserCreate
}

// Save creates the BackendUser entities in the database.
func (_c *BackendUserCreateBulk) Save(ctx context.Context) ([]*BackendUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BackendUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BackendUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BackendUserCreateBulk) SaveX(ctx context.Context) []*BackendUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BackendUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BackendUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
