// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ddevcap/jellymux/ent/backend"
	"github.com/ddevcap/jellymux/ent/backenduser"
	"github.com/ddevcap/jellymux/ent/user"
	"github.com/google/uuid"
)

// BackendUser is the model entity for the BackendUser schema.
type BackendUser struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// BackendUserID holds the value of the "backend_user_id" field.
	BackendUserID string `json:"backend_user_id,omitempty"`
	// BackendToken holds the value of the "backend_token" field.
	BackendToken *string `json:"-"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BackendUserQuery when eager-loading is set.
	Edges                 BackendUserEdges `json:"edges"`
	backend_backend_users *uuid.UUID
	user_backend_users    *uuid.UUID
	selectValues          sql.SelectValues
}

// BackendUserEdges holds the relations/edges for other nodes in the graph.
type BackendUserEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Backend holds the value of the backend edge.
	Backend *Backend `json:"backend,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BackendUserEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// BackendOrErr returns the Backend value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BackendUserEdges) BackendOrErr() (*Backend, error) {
	if e.Backend != nil {
		return e.Backend, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: backend.Label}
	}
	return nil, &NotLoadedError{edge: "backend"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BackendUser) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case backenduser.FieldEnabled:
			values[i] = new(sql.NullBool)
		case backenduser.FieldBackendUserID, backenduser.FieldBackendToken:
			values[i] = new(sql.NullString)
		case backenduser.FieldID:
			values[i] = new(uuid.UUID)
		case backenduser.ForeignKeys[0]: // backend_backend_users
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case backenduser.ForeignKeys[1]: // user_backend_users
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BackendUser fields.
func (_m *BackendUser) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case backenduser.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case backenduser.FieldBackendUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field backend_user_id", values[i])
			} else if value.Valid {
				_m.BackendUserID = value.String
			}
		case backenduser.FieldBackendToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field backend_token", values[i])
			} else if value.Valid {
				_m.BackendToken = new(string)
				*_m.BackendToken = value.String
			}
		case backenduser.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case backenduser.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field backend_backend_users", values[i])
			} else if value.Valid {
				_m.backend_backend_users = new(uuid.UUID)
				*_m.backend_backend_users = *value.S.(*uuid.UUID)
			}
		case backenduser.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_backend_users", values[i])
			} else if value.Valid {
				_m.user_backend_users = new(uuid.UUID)
				*_m.user_backend_users = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BackendUser.
// This includes values selected through modifiers, order, etc.
func (_m *BackendUser) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the BackendUser entity.
func (_m *BackendUser) QueryUser() *UserQuery {
	return NewBackendUserClient(_m.config).QueryUser(_m)
}

// QueryBackend queries the "backend" edge of the BackendUser entity.
func (_m *BackendUser) QueryBackend() *BackendQuery {
	return NewBackendUserClient(_m.config).QueryBackend(_m)
}

// Update returns a builder for updating this BackendUser.
// Note that you need to call BackendUser.Unwrap() before calling this method if this BackendUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BackendUser) Update() *BackendUserUpdateOne {
	return NewBackendUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BackendUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BackendUser) Unwrap() *BackendUser {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BackendUser is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BackendUser) String() string {
	var builder strings.Builder
	builder.WriteString("BackendUser(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("backend_user_id=")
	builder.WriteString(_m.BackendUserID)
	builder.WriteString(", ")
	builder.WriteString("backend_token=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteByte(')')
	return builder.String()
}

// BackendUsers is a parsable slice of BackendUser.
type BackendUsers []*BackendUser
