// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ddevcap/jellyfin-proxy/ent/backend"
	"github.com/google/uuid"
)

// Backend is the model entity for the Backend schema.
type Backend struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Base URL of the backend Jellyfin server, e.g. https://media.example.com
	URL string `json:"url,omitempty"`
	// ExternalID holds the value of the "external_id" field.
	ExternalID string `json:"external_id,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BackendQuery when eager-loading is set.
	Edges        BackendEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BackendEdges holds the relations/edges for other nodes in the graph.
type BackendEdges struct {
	// BackendUsers holds the value of the backend_users edge.
	BackendUsers []*BackendUser `json:"backend_users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// BackendUsersOrErr returns the BackendUsers value or an error if the edge
// was not loaded in eager-loading.
func (e BackendEdges) BackendUsersOrErr() ([]*BackendUser, error) {
	if e.loadedTypes[0] {
		return e.BackendUsers, nil
	}
	return nil, &NotLoadedError{edge: "backend_users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Backend) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case backend.FieldEnabled:
			values[i] = new(sql.NullBool)
		case backend.FieldName, backend.FieldURL, backend.FieldExternalID:
			values[i] = new(sql.NullString)
		case backend.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case backend.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Backend fields.
func (_m *Backend) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case backend.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case backend.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case backend.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case backend.FieldExternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_id", values[i])
			} else if value.Valid {
				_m.ExternalID = value.String
			}
		case backend.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case backend.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Backend.
// This includes values selected through modifiers, order, etc.
func (_m *Backend) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBackendUsers queries the "backend_users" edge of the Backend entity.
func (_m *Backend) QueryBackendUsers() *BackendUserQuery {
	return NewBackendClient(_m.config).QueryBackendUsers(_m)
}

// Update returns a builder for updating this Backend.
// Note that you need to call Backend.Unwrap() before calling this method if this Backend
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Backend) Update() *BackendUpdateOne {
	return NewBackendClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Backend entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Backend) Unwrap() *Backend {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Backend is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Backend) String() string {
	var builder strings.Builder
	builder.WriteString("Backend(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("external_id=")
	builder.WriteString(_m.ExternalID)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Backends is a parsable slice of Backend.
type Backends []*Backend
