// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ddevcap/jellymux/ent/backend"
	"github.com/ddevcap/jellymux/ent/backenduser"
	"github.com/ddevcap/jellymux/ent/predicate"
	"github.com/ddevcap/jellymux/ent/user"
	"github.com/google/uuid"
)

// BackendUserQuery is the builder for querying BackendUser entities.
type BackendUserQuery struct {
	config
	ctx         *QueryContext
	order       []backenduser.OrderOption
	inters      []Interceptor
	predicates  []predicate.BackendUser
	withUser    *UserQuery
	withBackend *BackendQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BackendUserQuery builder.
func (_q *BackendUserQuery) Where(ps ...predicate.BackendUser) *BackendUserQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *BackendUserQuery) Limit(limit int) *BackendUserQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *BackendUserQuery) Offset(offset int) *BackendUserQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *BackendUserQuery) Unique(unique bool) *BackendUserQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *BackendUserQuery) Order(o ...backenduser.OrderOption) *BackendUserQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *BackendUserQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(backenduser.Table, backenduser.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, backenduser.UserTable, backenduser.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBackend chains the current query on the "backend" edge.
func (_q *BackendUserQuery) QueryBackend() *BackendQuery {
	query := (&BackendClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(backenduser.Table, backenduser.FieldID, selector),
			sqlgraph.To(backend.Table, backend.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, backenduser.BackendTable, backenduser.BackendColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BackendUser entity from the query.
// Returns a *NotFoundError when no BackendUser was found.
func (_q *BackendUserQuery) First(ctx context.Context) (*BackendUser, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{backenduser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *BackendUserQuery) FirstX(ctx context.Context) *BackendUser {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BackendUser ID from the query.
// Returns a *NotFoundError when no BackendUser ID was found.
func (_q *BackendUserQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{backenduser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *BackendUserQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BackendUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BackendUser entity is found.
// Returns a *NotFoundError when no BackendUser entities are found.
func (_q *BackendUserQuery) Only(ctx context.Context) (*BackendUser, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{backenduser.Label}
	default:
		return nil, &NotSingularError{backenduser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *BackendUserQuery) OnlyX(ctx context.Context) *BackendUser {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BackendUser ID in the query.
// Returns a *NotSingularError when more than one BackendUser ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *BackendUserQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{backenduser.Label}
	default:
		err = &NotSingularError{backenduser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *BackendUserQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BackendUsers.
func (_q *BackendUserQuery) All(ctx context.Context) ([]*BackendUser, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BackendUser, *BackendUserQuery]()
	return withInterceptors[[]*BackendUser](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *BackendUserQuery) AllX(ctx context.Context) []*BackendUser {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BackendUser IDs.
func (_q *BackendUserQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(backenduser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *BackendUserQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *BackendUserQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*BackendUserQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *BackendUserQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *BackendUserQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *BackendUserQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BackendUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *BackendUserQuery) Clone() *BackendUserQuery {
	if _q == nil {
		return nil
	}
	return &BackendUserQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]backenduser.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.BackendUser{}, _q.predicates...),
		withUser:    _q.withUser.Clone(),
		withBackend: _q.withBackend.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BackendUserQuery) WithUser(opts ...func(*UserQuery)) *BackendUserQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithBackend tells the query-builder to eager-load the nodes that are connected to
// the "backend" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *BackendUserQuery) WithBackend(opts ...func(*BackendQuery)) *BackendUserQuery {
	query := (&BackendClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBackend = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		BackendUserID string `json:"backend_user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BackendUser.Query().
//		GroupBy(backenduser.FieldBackendUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *BackendUserQuery) GroupBy(field string, fields ...string) *BackendUserGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BackendUserGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = backenduser.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		BackendUserID string `json:"backend_user_id,omitempty"`
//	}
//
//	client.BackendUser.Query().
//		Select(backenduser.FieldBackendUserID).
//		Scan(ctx, &v)
func (_q *BackendUserQuery) Select(fields ...string) *BackendUserSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &BackendUserSelect{BackendUserQuery: _q}
	sbuild.label = backenduser.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BackendUserSelect configured with the given aggregations.
func (_q *BackendUserQuery) Aggregate(fns ...AggregateFunc) *BackendUserSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *BackendUserQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !backenduser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *BackendUserQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BackendUser, error) {
	var (
		nodes       = []*BackendUser{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withUser != nil,
			_q.withBackend != nil,
		}
	)
	if _q.withUser != nil || _q.withBackend != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, backenduser.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BackendUser).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BackendUser{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *BackendUser, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withBackend; query != nil {
		if err := _q.loadBackend(ctx, query, nodes, nil,
			func(n *BackendUser, e *Backend) { n.Edges.Backend = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *BackendUserQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*BackendUser, init func(*BackendUser), assign func(*BackendUser, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*BackendUser)
	for i := range nodes {
		if nodes[i].user_backend_users == nil {
			continue
		}
		fk := *nodes[i].user_backend_users
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_backend_users" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *BackendUserQuery) loadBackend(ctx context.Context, query *BackendQuery, nodes []*BackendUser, init func(*BackendUser), assign func(*BackendUser, *Backend)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*BackendUser)
	for i := range nodes {
		if nodes[i].backend_backend_users == nil {
			continue
		}
		fk := *nodes[i].backend_backend_users
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(backend.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "backend_backend_users" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *BackendUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *BackendUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(backenduser.Table, backenduser.Columns, sqlgraph.NewFieldSpec(backenduser.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, backenduser.FieldID)
		for i := range fields {
			if fields[i] != backenduser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *BackendUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(backenduser.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = backenduser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BackendUserGroupBy is the group-by builder for BackendUser entities.
type BackendUserGroupBy struct {
	selector
	build *BackendUserQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *BackendUserGroupBy) Aggregate(fns ...AggregateFunc) *BackendUserGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *BackendUserGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BackendUserQuery, *BackendUserGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *BackendUserGroupBy) sqlScan(ctx context.Context, root *BackendUserQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BackendUserSelect is the builder for selecting fields of BackendUser entities.
type BackendUserSelect struct {
	*BackendUserQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *BackendUserSelect) Aggregate(fns ...AggregateFunc) *BackendUserSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *BackendUserSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BackendUserQuery, *BackendUserSelect](ctx, _s.BackendUserQuery, _s, _s.inters, v)
}

func (_s *BackendUserSelect) sqlScan(ctx context.Context, root *BackendUserQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
