// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/ddevcap/jellyfin-proxy/ent/backend"
	"github.com/ddevcap/jellyfin-proxy/ent/backenduser"
	"github.com/ddevcap/jellyfin-proxy/ent/schema"
	"github.com/ddevcap/jellyfin-proxy/ent/session"
	"github.com/ddevcap/jellyfin-proxy/ent/user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	backendFields := schema.Backend{}.Fields()
	_ = backendFields
	// backendDescName is the schema descriptor for name field.
	backendDescName := backendFields[1].Descriptor()
	// backend.NameValidator is a validator for the "name" field. It is called by the builders before save.
	backend.NameValidator = backendDescName.Validators[0].(func(string) error)
	// backendDescURL is the schema descriptor for url field.
	backendDescURL := backendFields[2].Descriptor()
	// backend.URLValidator is a validator for the "url" field. It is called by the builders before save.
	backend.URLValidator = backendDescURL.Validators[0].(func(string) error)
	// backendDescJellyfinServerID is the schema descriptor for jellyfin_server_id field.
	backendDescJellyfinServerID := backendFields[3].Descriptor()
	// backend.JellyfinServerIDValidator is a validator for the "jellyfin_server_id" field. It is called by the builders before save.
	backend.JellyfinServerIDValidator = backendDescJellyfinServerID.Validators[0].(func(string) error)
	// backendDescPrefix is the schema descriptor for prefix field.
	backendDescPrefix := backendFields[4].Descriptor()
	// backend.PrefixValidator is a validator for the "prefix" field. It is called by the builders before save.
	backend.PrefixValidator = func() func(string) error {
		validators := backendDescPrefix.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(prefix string) error {
			for _, fn := range fns {
				if err := fn(prefix); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// backendDescEnabled is the schema descriptor for enabled field.
	backendDescEnabled := backendFields[5].Descriptor()
	// backend.DefaultEnabled holds the default value on creation for the enabled field.
	backend.DefaultEnabled = backendDescEnabled.Default.(bool)
	// backendDescCreatedAt is the schema descriptor for created_at field.
	backendDescCreatedAt := backendFields[6].Descriptor()
	// backend.DefaultCreatedAt holds the default value on creation for the created_at field.
	backend.DefaultCreatedAt = backendDescCreatedAt.Default.(func() time.Time)
	// backendDescID is the schema descriptor for id field.
	backendDescID := backendFields[0].Descriptor()
	// backend.DefaultID holds the default value on creation for the id field.
	backend.DefaultID = backendDescID.Default.(func() uuid.UUID)
	backenduserFields := schema.BackendUser{}.Fields()
	_ = backenduserFields
	// backenduserDescBackendUserID is the schema descriptor for backend_user_id field.
	backenduserDescBackendUserID := backenduserFields[1].Descriptor()
	// backenduser.BackendUserIDValidator is a validator for the "backend_user_id" field. It is called by the builders before save.
	backenduser.BackendUserIDValidator = backenduserDescBackendUserID.Validators[0].(func(string) error)
	// backenduserDescEnabled is the schema descriptor for enabled field.
	backenduserDescEnabled := backenduserFields[3].Descriptor()
	// backenduser.DefaultEnabled holds the default value on creation for the enabled field.
	backenduser.DefaultEnabled = backenduserDescEnabled.Default.(bool)
	// backenduserDescID is the schema descriptor for id field.
	backenduserDescID := backenduserFields[0].Descriptor()
	// backenduser.DefaultID holds the default value on creation for the id field.
	backenduser.DefaultID = backenduserDescID.Default.(func() uuid.UUID)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescToken is the schema descriptor for token field.
	sessionDescToken := sessionFields[1].Descriptor()
	// session.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	session.TokenValidator = sessionDescToken.Validators[0].(func(string) error)
	// sessionDescDeviceID is the schema descriptor for device_id field.
	sessionDescDeviceID := sessionFields[2].Descriptor()
	// session.DeviceIDValidator is a validator for the "device_id" field. It is called by the builders before save.
	session.DeviceIDValidator = sessionDescDeviceID.Validators[0].(func(string) error)
	// sessionDescDeviceName is the schema descriptor for device_name field.
	sessionDescDeviceName := sessionFields[3].Descriptor()
	// session.DeviceNameValidator is a validator for the "device_name" field. It is called by the builders before save.
	session.DeviceNameValidator = sessionDescDeviceName.Validators[0].(func(string) error)
	// sessionDescAppName is the schema descriptor for app_name field.
	sessionDescAppName := sessionFields[4].Descriptor()
	// session.AppNameValidator is a validator for the "app_name" field. It is called by the builders before save.
	session.AppNameValidator = sessionDescAppName.Validators[0].(func(string) error)
	// sessionDescLastActivity is the schema descriptor for last_activity field.
	sessionDescLastActivity := sessionFields[6].Descriptor()
	// session.DefaultLastActivity holds the default value on creation for the last_activity field.
	session.DefaultLastActivity = sessionDescLastActivity.Default.(func() time.Time)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[7].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[0].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescDisplayName is the schema descriptor for display_name field.
	userDescDisplayName := userFields[2].Descriptor()
	// user.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	user.DisplayNameValidator = userDescDisplayName.Validators[0].(func(string) error)
	// userDescHashedPassword is the schema descriptor for hashed_password field.
	userDescHashedPassword := userFields[3].Descriptor()
	// user.HashedPasswordValidator is a validator for the "hashed_password" field. It is called by the builders before save.
	user.HashedPasswordValidator = userDescHashedPassword.Validators[0].(func(string) error)
	// userDescIsAdmin is the schema descriptor for is_admin field.
	userDescIsAdmin := userFields[4].Descriptor()
	// user.DefaultIsAdmin holds the default value on creation for the is_admin field.
	user.DefaultIsAdmin = userDescIsAdmin.Default.(bool)
	// userDescDirectStream is the schema descriptor for direct_stream field.
	userDescDirectStream := userFields[5].Descriptor()
	// user.DefaultDirectStream holds the default value on creation for the direct_stream field.
	user.DefaultDirectStream = userDescDirectStream.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[6].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[7].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
