// Code generated by ent, DO NOT EDIT.

package backenduser

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ddevcap/jellymux/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldLTE(FieldID, id))
}

// BackendUserID applies equality check predicate on the "backend_user_id" field. It's identical to BackendUserIDEQ.
func BackendUserID(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldEQ(FieldBackendUserID, v))
}

// BackendToken applies equality check predicate on the "backend_token" field. It's identical to BackendTokenEQ.
func BackendToken(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldEQ(FieldBackendToken, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldEQ(FieldEnabled, v))
}

// BackendUserIDEQ applies the EQ predicate on the "backend_user_id" field.
func BackendUserIDEQ(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldEQ(FieldBackendUserID, v))
}

// BackendUserIDNEQ applies the NEQ predicate on the "backend_user_id" field.
func BackendUserIDNEQ(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldNEQ(FieldBackendUserID, v))
}

// BackendUserIDIn applies the In predicate on the "backend_user_id" field.
func BackendUserIDIn(vs ...string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldIn(FieldBackendUserID, vs...))
}

// BackendUserIDNotIn applies the NotIn predicate on the "backend_user_id" field.
func BackendUserIDNotIn(vs ...string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldNotIn(FieldBackendUserID, vs...))
}

// BackendUserIDGT applies the GT predicate on the "backend_user_id" field.
func BackendUserIDGT(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldGT(FieldBackendUserID, v))
}

// BackendUserIDGTE applies the GTE predicate on the "backend_user_id" field.
func BackendUserIDGTE(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldGTE(FieldBackendUserID, v))
}

// BackendUserIDLT applies the LT predicate on the "backend_user_id" field.
func BackendUserIDLT(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldLT(FieldBackendUserID, v))
}

// BackendUserIDLTE applies the LTE predicate on the "backend_user_id" field.
func BackendUserIDLTE(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldLTE(FieldBackendUserID, v))
}

// BackendUserIDContains applies the Contains predicate on the "backend_user_id" field.
func BackendUserIDContains(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldContains(FieldBackendUserID, v))
}

// BackendUserIDHasPrefix applies the HasPrefix predicate on the "backend_user_id" field.
func BackendUserIDHasPrefix(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldHasPrefix(FieldBackendUserID, v))
}

// BackendUserIDHasSuffix applies the HasSuffix predicate on the "backend_user_id" field.
func BackendUserIDHasSuffix(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldHasSuffix(FieldBackendUserID, v))
}

// BackendUserIDEqualFold applies the EqualFold predicate on the "backend_user_id" field.
func BackendUserIDEqualFold(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldEqualFold(FieldBackendUserID, v))
}

// BackendUserIDContainsFold applies the ContainsFold predicate on the "backend_user_id" field.
func BackendUserIDContainsFold(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldContainsFold(FieldBackendUserID, v))
}

// BackendTokenEQ applies the EQ predicate on the "backend_token" field.
func BackendTokenEQ(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldEQ(FieldBackendToken, v))
}

// BackendTokenNEQ applies the NEQ predicate on the "backend_token" field.
func BackendTokenNEQ(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldNEQ(FieldBackendToken, v))
}

// BackendTokenIn applies the In predicate on the "backend_token" field.
func BackendTokenIn(vs ...string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldIn(FieldBackendToken, vs...))
}

// BackendTokenNotIn applies the NotIn predicate on the "backend_token" field.
func BackendTokenNotIn(vs ...string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldNotIn(FieldBackendToken, vs...))
}

// BackendTokenGT applies the GT predicate on the "backend_token" field.
func BackendTokenGT(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldGT(FieldBackendToken, v))
}

// BackendTokenGTE applies the GTE predicate on the "backend_token" field.
func BackendTokenGTE(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldGTE(FieldBackendToken, v))
}

// BackendTokenLT applies the LT predicate on the "backend_token" field.
func BackendTokenLT(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldLT(FieldBackendToken, v))
}

// BackendTokenLTE applies the LTE predicate on the "backend_token" field.
func BackendTokenLTE(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldLTE(FieldBackendToken, v))
}

// BackendTokenContains applies the Contains predicate on the "backend_token" field.
func BackendTokenContains(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldContains(FieldBackendToken, v))
}

// BackendTokenHasPrefix applies the HasPrefix predicate on the "backend_token" field.
func BackendTokenHasPrefix(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldHasPrefix(FieldBackendToken, v))
}

// BackendTokenHasSuffix applies the HasSuffix predicate on the "backend_token" field.
func BackendTokenHasSuffix(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldHasSuffix(FieldBackendToken, v))
}

// BackendTokenIsNil applies the IsNil predicate on the "backend_token" field.
func BackendTokenIsNil() predicate.BackendUser {
	return predicate.BackendUser(sql.FieldIsNull(FieldBackendToken))
}

// BackendTokenNotNil applies the NotNil predicate on the "backend_token" field.
func BackendTokenNotNil() predicate.BackendUser {
	return predicate.BackendUser(sql.FieldNotNull(FieldBackendToken))
}

// BackendTokenEqualFold applies the EqualFold predicate on the "backend_token" field.
func BackendTokenEqualFold(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldEqualFold(FieldBackendToken, v))
}

// BackendTokenContainsFold applies the ContainsFold predicate on the "backend_token" field.
func BackendTokenContainsFold(v string) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldContainsFold(FieldBackendToken, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.BackendUser {
	return predicate.BackendUser(sql.FieldNEQ(FieldEnabled, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.BackendUser {
	return predicate.BackendUser(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.BackendUser {
	return predicate.BackendUser(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBackend applies the HasEdge predicate on the "backend" edge.
func HasBackend() predicate.BackendUser {
	return predicate.BackendUser(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BackendTable, BackendColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBackendWith applies the HasEdge predicate on the "backend" edge with a given conditions (other predicates).
func HasBackendWith(preds ...predicate.Backend) predicate.BackendUser {
	return predicate.BackendUser(func(s *sql.Selector) {
		step := newBackendStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BackendUser) predicate.BackendUser {
	return predicate.BackendUser(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BackendUser) predicate.BackendUser {
	return predicate.BackendUser(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BackendUser) predicate.BackendUser {
	return predicate.BackendUser(sql.NotPredicates(p))
}
